repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=no]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.28.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@7.28.0
                - eslint-config-standard@16.0.3
                - eslint-config-prettier@8.3.0
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.3.1
      hooks:
          - id: prettier
    - repo: https://github.com/psf/black
      rev: 21.5b2
      hooks:
          - id: black
