exclude: ^web/static/vendored/.+$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=no]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.28.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@7.28.0
                - eslint-config-standard@16.0.3
                - eslint-config-prettier@8.3.0
                - "@typescript-eslint/parser@4.28.1"
                - "@typescript-eslint/eslint-plugin@4.28.1"
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.3.1
      hooks:
          - id: prettier
            exclude_types: [html]
    - repo: https://github.com/PyCQA/isort
      rev: 5.8.0
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 21.6b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear~=21.4
                - flake8-pytest-style~=1.5
                - pep8-naming~=0.11
