version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:8000:8000"
        tty: true
        init: true
        environment:
            FLASK_ENV: development
        volumes:
            - .:/recipes:ro
