import flask
import pytest


SPOONACULAR_BASE = "https://api.spoonacular.com/recipes/"
ENDPOINT_MAP = (("api.search_api", "complexSearch"), ("api.ingredient_api", "parseIngredients"))


@pytest.mark.parametrize("endpoint,spoonacular_endpoint", ENDPOINT_MAP)
def test_endpoints_success(client, requests_mock, endpoint, spoonacular_endpoint):
    """On success, Spoonacular's response should be forwarded with a 200 status code."""
    data = dict(hello="world")
    requests_mock.get(SPOONACULAR_BASE + spoonacular_endpoint, json=data)

    res = client.get(flask.url_for(endpoint))

    assert res.status_code == 200
    assert res.get_json() == data


@pytest.mark.parametrize("endpoint,spoonacular_endpoint", ENDPOINT_MAP)
@pytest.mark.options(SPOONACULAR_KEY="test_key")
def test_args_forwarded(client, requests_mock, endpoint, spoonacular_endpoint):
    """Arguments should be forwarded to the Spoonacular request and the API key should be passed."""
    requests_mock.get(SPOONACULAR_BASE + spoonacular_endpoint, json={})

    client.get(flask.url_for(endpoint, hello="world"))

    # qs is generated by urllib.parse.parse_qs, which puts values in lists.
    assert requests_mock.last_request.qs == dict(apikey=["test_key"], hello=["world"])


@pytest.mark.parametrize("endpoint,spoonacular_endpoint", ENDPOINT_MAP)
def test_spoonacular_error_forwarded(client, requests_mock, endpoint, spoonacular_endpoint):
    """Response and status code should be forwarded from Spoonacular upon failure."""
    data = dict(
        status="failure",
        code=401,
        message="You are not authorized. Please read ...",
    )
    requests_mock.get(
        SPOONACULAR_BASE + spoonacular_endpoint,
        json=data,
        status_code=data["code"],
        headers={"content-type": "application/json"},
    )

    res = client.get(flask.url_for(endpoint))

    assert res.status_code == data["code"]
    assert res.get_json() == data


@pytest.mark.parametrize("param", ("fillIngredients", "addRecipeNutrition"))
@pytest.mark.parametrize("value,expected_status", (("true", 403), ("false", 200)))
def test_search_disabled_params(client, requests_mock, param, value, expected_status):
    """Search endpoint should return 403 when disabled params are true, and 200 when false."""
    requests_mock.get(SPOONACULAR_BASE + "complexSearch", json={})

    res = client.get(flask.url_for("api.search_api", **{param: value}))

    assert res.status_code == expected_status
