name: Build

on:
    workflow_run:
        workflows: ["Lint & Test"]
        branches:
            - main
        types:
            - completed

jobs:
    build:
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
        name: Build & Push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to AWS ECR
              uses: docker/login-action@v1
              with:
                  registry: public.ecr.aws
                  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              env:
                  AWS_REGION: us-west-1
              if: false # Disabled until we have an AWS account ready

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: false
                  # cache-from: type=registry,ref=public.ecr.aws/name/recipes:latest
                  cache-to: type=inline
                  # tags: public.ecr.aws/name/recipes:latest
